/* my_machine.h - GENERATED by build-grblhal.ps1 - do not edit by hand. */
/* Baseline = grblHAL 'generic board' defaults (Native USB, probe, PWM spindle, grblHAL compat). */


// --- baseline (default) flags ---
#define USB_SERIAL_CDC      1   // Native USB CDC
#define COMPATIBILITY_LEVEL 0   // grblHAL native -> ESTOP_ENABLE defaults to 1

// --- spindle(s) ---
// (none specified -> default on-board PWM spindle is instantiated)

// --- machine tuning (driver-level) ---
#define ESTOP_ENABLE 0
#define CONTROL_ENABLE 0

// --- networking daemons (auto, keyed off CMake-set WIFI/ETHERNET) ---
#if WIFI_ENABLE || ETHERNET_ENABLE || WEBUI_ENABLE
#define TELNET_ENABLE        1
#define WEBSOCKET_ENABLE     1
#if SDCARD_ENABLE || WEBUI_ENABLE
#define FTP_ENABLE           1
#endif
#endif

/**/
